# 任务的名称
name: deploy-docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest # 运行环境

    strategy:
      matrix:
        node-version: [ 18.12.0 ] # node 版本

    steps:
      # 检出项目
      - name: Checkout
        uses: actions/checkout@v2

      # 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      # 使用特定版本的 node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Pnpm config
        run: pnpm config set registry https://registry.npmmirror.com # 设置为官方镜像

      - name: Install deps
        run: pnpm install # 下载依赖

      - name: Build docs
        run: pnpm docs:build # 执行打包命令

      # 部署 vitepress
      - name: Deploy-docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist # 这里是打包后文件的目录
